spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/mecanix_db
spring.datasource.username=postgres
spring.datasource.password=T@ti1320
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=America/Sao_Paulo

server.port=8080

# E-mail Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mecanixteste@gmail.com
spring.mail.password=umezblkaqqttvuvy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
mecanix.mail.remetente=mecanixteste@gmail.com

logging.level.com.mecanix=INFO
logging.level.org.springframework=WARN


